---
title: "Chữa bài tập về nhà"
author: "Mai Hoàng Đức"
date: "2023-12-07"
output: html_document
---
Bài 1
```{r setup, include=FALSE}
# Dữ liệu
khoan_chi_tieu <- c("Quốc phòng", "An ninh xã hội", "Y tế", "Trả lãi nợ quốc gia", "Các chương trình xã hội", "Các chi phí khác")
so_tien_chi <- c(525, 500, 500, 300, 200, 475)

# a. Vẽ biểu đồ tròn
pie(so_tien_chi, main = "Phân bố chi tiêu của Chính phủ Mỹ trong năm 2006", col = c("red","magenta", "green", "blue", "orange","yellow"))
legend("topleft", c("Quốc phòng", "An ninh xã hội", "Y tế", "Trả lãi nợ quốc gia", "Các chương trình xã hội", "Các chi phí khác"),
fill =c("red","magenta", "green", "blue", "orange","yellow"), cex = 0.6)



# b. Vẽ biểu đồ cột
barplot(so_tien_chi, col = c("red","magenta", "green", "blue", "orange","yellow"), xlab = "Các khoản chi tiêu", main = "Phân bố chi tiêu của Chính phủ Mỹ trong năm 2006", ylab = "Số tiền đã chi")
legend("topleft", c("Quốc phòng", "An ninh xã hội", "Y tế", "Trả lãi nợ quốc gia", "Các chương trình xã hội", "Các chi phí khác"),
fill =c("red","magenta", "green", "blue", "orange","yellow"), cex = 0.6)
mtext("Tỷ đô", at = 0.3)


# c. Vẽ lại 2 biểu đồ trên sử dụng giá trị phần trăm
so_tien_tong = sum(so_tien_chi)
phan_tram_chi = so_tien_chi / so_tien_tong * 100

# Biểu đồ tròn với phần trăm
par(mfrow = c(1,2))
par(mar = c(6, 6, 1, 1))
pie(phan_tram_chi, labels = paste(khoan_chi_tieu, "\n", sprintf("%.1f%%", phan_tram_chi)), main = "Phân bố chi tiêu của Chính phủ Mỹ trong năm 2006")

# Biểu đồ cột với phần trăm
barplot(phan_tram_chi, names.arg = khoan_chi_tieu, col = "skyblue", main = "Phân bố chi tiêu của Chính phủ Mỹ trong năm 2006", ylab = "Tỷ lệ phần trăm")

```

Bài 6
```{r cars}
# Cài đặt và tải gói Stat2Data
install.packages("Stat2Data")
library(Stat2Data)
View(AHCAvote2017)

# Tải dữ liệu AHCAVote2017 từ gói Stat2Data
data("AHCAvote2017")

# 1. Bảng tần số về số thành viên của quốc hội theo từng bang
table_bang <- table(AHCAvote2017$STATE, AHCAvote2017$Member)
print("1. Bảng tần số về số thành viên của quốc hội theo từng bang:")
print(table_bang)

# 2. Bảng tần số giữa kết quả phiếu bầu đạo luật (AHCAvote) và kết quả bầu tổng thống trước đó (Trump)
table_vote_president <- table(AHCAvote2017$AHCAvote, AHCAvote2017$Trump)
print("2. Bảng tần số giữa kết quả phiếu bầu đạo luật (AHCAvote) và kết quả bầu tổng thống trước đó (Trump):")
print(table_vote_president)

# 3. Biểu đồ cột về số thành viên quốc hội theo đảng Dân chủ (Democrat) và đảng Cộng hòa (Republican)
table_party <- table(AHCAvote2017$Party)
barplot(table_party, main = "Số thành viên quốc hội theo đảng", 
        xlab = "Đảng", ylab = "Số lượng thành viên",
        col = c("blue", "red"))

# 4. Biểu đồ tán xạ giữa cột uniChange và AHCAvote
plot(AHCAvote2017$uniChange, AHCAvote2017$AHCAvote, 
     main = "Biểu đồ tán xạ giữa uniChange và AHCAvote",
     xlab = "uniChange", ylab = "AHCAvote", col = "red", col.main = "magenta", col.axis = "blue", col.lab = "orange")

```

## Including Plots

Bài 4

```{r}

#Dữ liệu
x = c(0.75, 0.86, 0.84, 0.85, 0.97,
      0.94, 0.89, 0.84, 0.83, 0.89,
      0.88, 0.78, 0.77, 0.76, 0.82,
      0.72, 0.92, 1.05, 0.94, 0.83,
      0.81, 0.85, 0.97, 0.93, 0.79)

#Vẽ biểu đồ tán xạ
hist(x, breaks = seq(0.72, 1.1, by = 0.09), main = "Đại diện cho mức florua trong 25 ngày", xlim = c(0.7,1.1), ylim = c(0,25))


```

Bài 5

```{r}
#Dữ liệu
standard_therapy = c(4, 15, 24, 10, 1, 27, 31,
                     14, 2, 16, 32, 7, 13, 36,
                     29, 6, 12, 18, 14, 15, 18,
                     6, 13, 21, 20, 8, 3, 24)

new_therapy = c(5, 20, 29, 15, 7, 32, 36,
                17, 15, 19, 35, 10, 16, 39,
                27, 14, 10, 16, 12, 13, 16,
                9, 18, 33, 30, 29, 31, 27)

#Vẽ 2 biểu đồ cạnh nhau
par(mfrow = c(1,2))

#Biểu đồ Standard Therapy
hist(standard_therapy, breaks = seq(1, 39, by = 1), main = "Thời gian sống sót tính bằng tháng của bệnh nhân sử dụng phương pháp thông thường", xlim = c(1, 39), ylim = c(0, 39))

#Biểu đồ New Therapy
hist(new_therapy, breaks = seq(1, 39, by = 1), main = "Thời gian sống sót tính bằng tháng của bệnh nhân sử dụng phương pháp mới", xlim = c(1, 39), ylim = c(0,39))

#Kiểm tra đâu là phương pháp hiệu quả hơn

if (mean(standard_therapy) == mean(new_therapy)) {
  print("Thời gian sống của hai phương pháp điều trị là như nhau")
  } else if (mean(standard_therapy) > mean(new_therapy)) {
  print("Thời gian sống của phương pháp cũ lâu hơn phương pháp mới")
    } else {
  print("Thời gian sống của phương pháp mới lâu hơn phương pháp cũ")
  }
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
